version: '3'

tasks:

  init:*:
    vars:
      ENV: '{{index .MATCH 0}}'
    dotenv:
      - '{{ .ENV }}/.env'
    cmds:
      - terraform init -backend-config=environments/{{ .ENV }}/backend.tfvars

  validate:
    cmds:
      - terraform validate

  fmt:
    cmds:
      - terraform fmt -recursive

  plan:*:
    vars:
      ENV: '{{index .MATCH 0}}'
    dotenv:
      - '{{ .ENV }}/.env'
    cmds:
      - terraform plan -var-file=environments/{{ .ENV }}/terraform.tfvars -out plan.out

  apply:*:
    vars:
      ENV: '{{index .MATCH 0}}'
    dotenv:
      - '{{ .ENV }}/.env'
    cmds:
      - terraform apply -auto-approve plan.out

  destroy:*:
      vars:
        ENV: '{{index .MATCH 0}}'
      dotenv:
        - '{{ .ENV }}/.env'
      cmds:
        - terraform apply -destroy -auto-approve plan.out
